Controllers/DayDatasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EnergieWebApp.Data;
using EnergieWebApp.Models;

namespace EnergieWebApp.Controllers
{
    public class DayDatasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DayDatasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DayDatas
        public async Task<IActionResult> Index()
        {
              return _context.DayDatas != null ? 
                          View(await _context.DayDatas.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.DayDatas'  is null.");
        }

        // GET: DayDatas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DayDatas == null)
            {
                return NotFound();
            }

            var dayData = await _context.DayDatas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dayData == null)
            {
                return NotFound();
            }

            return View(dayData);
        }

        // GET: DayDatas/Create
        public IActionResult Create(int accID)
        {
            CreateDayDataModel m = new CreateDayDataModel();
            m.accID = accID;
            return View(m);
        }

        // POST: DayDatas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("accID,Date,Kwh")] CreateDayDataModel dayData)
        {
            
            if (ModelState.IsValid)
            {

                User user = _context.Users.Where(x => x.AccountId == dayData.accID).FirstOrDefault();
                DayData day = new DayData
                {
                    Account = user,
                    Kwh = dayData.Kwh,
                    Date = dayData.Date

                };
                _context.Add(day);
                await _context.SaveChangesAsync();
                return RedirectToAction("Close");
            }

            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    // Log or print the validation errors
                    Console.WriteLine(error.ErrorMessage);
                }
            }

            CreateDayDataModel m = new CreateDayDataModel();
            m.accID = dayData.accID;
            return View(m);
        }

        // GET: DayDatas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DayDatas == null)
            {
                return NotFound();
            }

            var dayData = await _context.DayDatas.FindAsync(id);
            if (dayData == null)
            {
                return NotFound();
            }
            return View(dayData);
        }

        // POST: DayDatas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Kwh")] DayData dayData)
        {
            if (id != dayData.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dayData);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DayDataExists(dayData.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dayData);
        }

        // GET: DayDatas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DayDatas == null)
            {
                return NotFound();
            }

            var dayData = await _context.DayDatas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dayData == null)
            {
                return NotFound();
            }

            return View(dayData);
        }

        // POST: DayDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DayDatas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.DayDatas'  is null.");
            }
            var dayData = await _context.DayDatas.FindAsync(id);
            if (dayData != null)
            {
                _context.DayDatas.Remove(dayData);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DayDataExists(int id)
        {
          return (_context.DayDatas?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public ActionResult Close()
        {
            return View();

        }
    }
}

Controllers/MyUsageController.cs
using EnergieWebApp.Data;
using EnergieWebApp.Models;
using EnergieWebApp.Modelview;
using Microsoft.AspNetCore.Mvc;

namespace EnergieWebApp.Controllers
{
    public class MyUsageController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MyUsageController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int accID)
        {


            User u = _context.Users.Where(u => u.AccountId == accID).FirstOrDefault();
            List<DayData> DayDatas = _context.DayDatas.Where(x => x.Account.Id == u.Id).OrderBy(x => x.Date).ToList();
            
            
            DateTime weekAgo = DateTime.Now.AddDays(-7);
            List<DayData> DayDatasWeek = _context.DayDatas.Where(x => x.Account.Id == u.Id && x.Date >= weekAgo).OrderBy(x => x.Date).ToList();
            int? weekAverage = null;
            
            if (DayDatasWeek.Count > 0)
            {
                foreach (DayData dayData in DayDatasWeek)
                {
                    weekAverage = (weekAverage ?? 0) + dayData.Kwh;
                }
                weekAverage = weekAverage / DayDatasWeek.Count;
            }


            MyUsageViewModel model = new MyUsageViewModel()
            {
                accID = accID,
                DayDatas = DayDatas,
                AverageKwh = weekAverage,
            };
            return View(model);
        }
    }
}

Views/MyUsage/Index.cshtml
@model EnergieWebApp.Modelview.MyUsageViewModel
@{
    ViewData["Title"] = "View";
    Layout = null;
}

<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<img class="banner" src="~/resources/banner.png" />

<head> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
</head>
<h1>View</h1>


<div class="MyUsageContent">
<canvas id="myChart" style="width:100%;max-width:700px"></canvas>

@if (Model.AverageKwh == null)
{
    <img class="advice" src="~/resources/Unknown.jpg">
}
else if(Model.AverageKwh < 3)
{
    <img class="advice" src="~/resources/Good.png">
    <h3> Goedbezig</h3>
    <p>er zijn altijd verbeteringen maar je bent goed op weg.</p>
}
else if (7 > Model.AverageKwh && Model.AverageKwh > 3)
{
    <img class="advice" src="~/resources/Neutral.png">
    <h3>normaal energie verbuirk</h3>
        <p>Kies voor energie-efficiënte apparaten bij vervanging</p>
        <p>Onderhoud je apparaten regelmatig voor maximale efficiëntie.</p>
}
else
{
    <img class="advice" src="~/resources/Bad.png">
    <h3 class="advicetext">Oei een hoog verbruik hier zijn een aantal tips:</h3>
        <p class="advicetext">Kies voor energie-efficiënte apparaten bij vervanging.</p>
        <p class="advicetext">Onderhoud je apparaten regelmatig voor maximale efficiëntie.</p>
}
</div>

<div class="myUsageButton">
    <a asp-controller="DayDatas" asp-action="Create" asp-route-accID="@Model.accID" target="_blank" class="textbutton">Dag toevoegen</a>
</div>

<script>
    var xValues = [];
    var yValues = [];

    @foreach (DayData dayData in Model.DayDatas)
    {
        <text>
        xValues.push("@dayData.Date.ToShortDateString()");
        yValues.push("@dayData.Kwh");
        </text>
    }

        new Chart("myChart", {
            type: "line",
            data: {
                labels: xValues,
                datasets: [{
                    fill: false,
                    lineTension: 0,
                    backgroundColor: "rgba(0,0,255,1.0)",
                    borderColor: "rgba(0,0,255,0.1)",
                    data: yValues
                }]
            },
            options: {
                legend: { display: false },
                scales: {
                    //yAxes: [{ ticks: { min: 0, max: 16 } }],
                }
            }
        });
</script>